In [22]:
# Quentin VU

import numpy as np 
import pandas as ps

### Problem 1  (0.5 points) 2min.

Fix the following code: 

In [ ]:
a = np.array([1, 2, 4, 5, 6])
b = a.copy() #20/11 editing by adding copy numpy method

b[2] = 4

In [ ]:
print(a) # a should be equal to its initial value

[1 2 4 5 6]


In [ ]:
grade = 0.25 # not the correct solution....

### Problem 2  (0.5 points)  2min.

Fix the following function (the code never stops): 

In [200]:
def create_array(n):
    res=[]
    i=1
    #adding i=i+1 instruction last version
    while i<=n: 
      res=[i]
      i=i+1
    print('Array res values: ')
    return res

In [ ]:
res.append(i)

In [199]:
create_array(100)

Array res values: 


[100, 100]

In [205]:
#Go further: alternative option(the code also stops )but displays each value i
def create_array1(n):
    res=[]
    i=1
    #adding i=i+1 instruction
    while i<=n: 
      res.append(i)
      i=i+1
    print('Array res values: ')
    return res

In [206]:
create_array1(100)

Array res values: 


[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [ ]:
grade += 0

### Problem 3  (1 point)  5-10min.

Fix the following function

In [ ]:
def eval_object(v):
    operations = { '+': v['a']+v['b'],
                   '-': v['a']-v['b'],
                   '/': v['a']/v['b'],
                   '*': v['a']*v['b'],
                   '%': v['a']%v['b'],
                   '**': v['a']**v['b']}
    if operations.keys()=='+':
        return operations['+']
    if operations.keys()=='-':
        return operations['-']
    if operations.keys()=='/':
        return operations['/']
    if operations.keys()=='*':
        return operations['*']
    if operations.keys()=='%':
        return operations['%']
    if operations.keys()=='**':
        return operations['**']

In [10]:
def eval_object(v):
    operations = { '+': v['a']+v['b'],
                   '-': v['a']-v['b'],
                   '/': v['a']/v['b'],
                   '*': v['a']*v['b'],
                   '%': v['a']%v['b'],
                   '**': v['a']**v['b']}
    #editing this code version 
    print('The respective values for each operation( +, -, /, *, %, **) are:')
    return operations.values()
  

In [11]:
print(eval_object({'a':1,'b':1,'operation':'+'}))  # should print 2
print(eval_object({'a':1,'b':1,'operation':'-'}))  # should print 0
print(eval_object({'a':1,'b':1,'operation':'/'}))  # should print 1
print(eval_object({'a':1,'b':1,'operation':'*'}))  # should print 1
print(eval_object({'a':1,'b':1,'operation':'%'}))  # should print 0
print(eval_object({'a':1,'b':1,'operation':'**'})) # should print 1

The respective values for each operation( +, -, /, *, %, **) are:
dict_values([2, 0, 1.0, 1, 0, 1])
The respective values for each operation( +, -, /, *, %, **) are:
dict_values([2, 0, 1.0, 1, 0, 1])
The respective values for each operation( +, -, /, *, %, **) are:
dict_values([2, 0, 1.0, 1, 0, 1])
The respective values for each operation( +, -, /, *, %, **) are:
dict_values([2, 0, 1.0, 1, 0, 1])
The respective values for each operation( +, -, /, *, %, **) are:
dict_values([2, 0, 1.0, 1, 0, 1])
The respective values for each operation( +, -, /, *, %, **) are:
dict_values([2, 0, 1.0, 1, 0, 1])


In [ ]:
grade += 0

### Problem 4  (1 point) 2min.

Fix the following code

In [ ]:
import numpy as np
images = np.random.rand(500, 48, 48, 3)
#min max images matrix random editing this code
imagesmin=images.min()
imagesmax=images.max()
normalized_images = (images-imagesmin)/(imagesmax-imagesmin)
#expected values: between 0 and 1
print(normalized_images)


[[[[0.2779507  0.88606901 0.91953085]
   [0.13889172 0.24380464 0.38455203]
   [0.35094918 0.30458863 0.82320796]
   ...
   [0.84214074 0.65109786 0.58023872]
   [0.64704845 0.25868187 0.57363622]
   [0.19983199 0.47890298 0.98877562]]

  [[0.04366031 0.29125578 0.74338023]
   [0.52521709 0.97152845 0.25232671]
   [0.97679554 0.08736839 0.24962136]
   ...
   [0.79424536 0.70159336 0.79628479]
   [0.75206959 0.17130506 0.4608602 ]
   [0.50419356 0.70219473 0.56707053]]

  [[0.77608965 0.68326991 0.97713199]
   [0.03054989 0.74874171 0.17116992]
   [0.52807593 0.21385206 0.81482443]
   ...
   [0.89760622 0.6444475  0.24927007]
   [0.47879388 0.0019276  0.61738119]
   [0.59822774 0.72175598 0.07066179]]

  ...

  [[0.0394709  0.72377717 0.23417097]
   [0.98085698 0.80378884 0.21305422]
   [0.47875295 0.663538   0.67021159]
   ...
   [0.23311499 0.41327994 0.83557483]
   [0.60038349 0.80749591 0.23233067]
   [0.39660017 0.84605861 0.90813699]]

  [[0.68431466 0.57062703 0.67035437]
   [0.9

In [ ]:
grade += 0 # the code does not do the same thing as it was supposed to

### Problem 5   (2 points) 15min.

You are given a matrix represented by a list of lists. Write a function transpose such that it return a transposed matrix without changing an initial one. Verify on several tests. NumPy is not allowed.

**Example**

`
test_matrix = [[1, 2], [3, 4]]
print(transposition(test_matrix))
[[1, 3],
[2, 4]]`


In [ ]:
#first try in exam
def transposition1(test_matrix):
    #replace pass by your code  on utilise .copy()
    result = [[0,0],[0,0]]
    # iterate through rows
    for i in range(len(test_matrix)):
    # iterate through columns
      for j in range(len(test_matrix[0])):
        result[j][i] = test_matrix[i][j]
  
    return result




In [140]:
#second try transposition adding method in updated version
def transposition(test_matrix):
  MT = []
  for i in range(len(test_matrix)):
    MT.append([row[i] for row in test_matrix])
  return MT

In [141]:
#test 1
test_matrix = [[1, 2], [3, 4]]
#expected matrix transpose:[[1, 3], [2, 4]]
transposition(test_matrix)

[[1, 3], [2, 4]]

In [142]:
#test 2
test_matrix= [[1, 5], [3, 4]]
#expected matrix transpose:[[1, 3], [5, 4]]
transposition(test_matrix)

[[1, 3], [5, 4]]

In [143]:
#test 3
test_matrix= [[8, 5], [0, 4]]
#expected matrix transpose:[[8, 0], [5, 4]]
transposition(test_matrix)

[[8, 0], [5, 4]]

In [145]:
#test 3
test_matrix= [[8, 6], [1, 4]]
#expected matrix transpose:[[8, 1], [6, 4]]
transposition(test_matrix)

[[8, 1], [6, 4]]

In [ ]:
grade += 1

### Problem 6   (3 points)  15min.

Write a class circle defining a cicrle with a center `(x, y)` and radius `r` having following methods: 

* `__init__` -- circle initialization
* `is_in_circle` -- method returning `true` if point (x, y) is inside or at the circle and `else` otherwise.
* `is_in_circle_vectorized` -- method taking an argument `points` returning a boolean array of size `N`, where `true`-s correspond to points inside or at the circle and `false`-s correspond to those outside. `points.shape = (N, 2)`.

**Example**

`
c = circle((1., 1.), 5.)
print(c.is_in_circle(2., 2.))
True
print(c.is_in_circle_vectorized(np.array([[1., 1.], [2., 2.], [8., 8.]])))
[True, True, False]`


In [147]:
class Circle(object): 

    #replace pass by your code     updated version
   def __init__(self, center, r): # (x, y) should be treated as tuple 
        super(Circle, self).__init__()
        self.center = center
        x, y = center
        self.radius=r
        if not isinstance(center, tuple):
            raise TypeError("The center must be a tuple!")
   def is_in_circle(self,center):  # self is missing
        circleis=True
        #pythagore theorem
        if  self.center[0]**2+self.center[1]**2<=self.radius**2:
            circleis=True
        else:
            circleis=False
        return circleis
    
   def is_in_circle_vectorized(self,points): # self is missing
        arrayboolean=[False]*len(points)
        ownedcircle=is_in_circle(self.center,self.r)
        for compte in points:
            if ownedcircle==True:
                arrayboolean[compte]=True
            else:
                arrayboolean[compte]=False
        return arrayboolean

In [148]:
c1 = Circle((1., 1.),5)
print(c)

In [149]:

print(c1.is_in_circle(2, 2))
print(c1.is_in_circle_vectorized(np.array([[1., 1.], [2., 2.], [8., 8.]])))

TypeError: ignored

In [ ]:
grade += 1 # even if it does not work at all

### Problem 7   (2 points) 15min.

Write a function `reorder` getting integers `N`, `K` and `M` and returning an array with `K` sub-arrays with numbers in ranges `[0, N//K), [N//K + 1, 2*N//K)` ... `[(K-1)*N//K + 1, N)`, each of them being rotated `M` times (for rotation you can use `np.roll`).



**Example**
                                                                                                                
`
reorder(10, 2, 1)   =>  [[4, 0, 1, 2, 3], [9, 5, 6, 7, 8]]
reorder(10, 2, 3)   =>  [[2, 3, 4, 0, 1], [7, 8, 9, 5, 6]]
reorder(10, 2, 97)  =>  [[3, 4, 0, 1, 2], [8, 9, 5, 6, 7]]                                                                                                                       
`


In [ ]:
#second try at reorder function updating 20/11 algorithm version
def reorder(N, K, M):
    #replace pass by your code
    matriceg=[]  # should not be hardcoded
    matriced=[]
    #append elements for matriceg and matriced arrays
    for i in range(int(N/K)):
      #add i in matriceg array
      matriceg.append(i)
    #print('left side',matriceg)
    for j in range(int(N/K), N):
       #add i in matriced array
      matriced.append(j)
    #print('right side',matriced)
    arraydepart=np.concatenate((matriceg,matriced))
    #To do un roll at matriceg
    matrixrotate=np.roll(matriceg,M)
    #To do un roll at matriced
    matrixrotate1=np.roll(matriced,M)
    arraytotal=np.array([matrixrotate,matrixrotate1])
    return arraytotal
        
    
        
print('reorder(10,2,1):')
print(reorder(10, 2, 1))#expected  [[4, 0, 1, 2, 3], [9, 5, 6, 7, 8]]
print('reorder(10,2,3):')
print(reorder(10, 2, 3))#expected [[2, 3, 4, 0, 1], [7, 8, 9, 5, 6]]
print('reorder(10,2,97):')
print(reorder(10, 2, 97))#expected [[3, 4, 0, 1, 2], [8, 9, 5, 6, 7]]

grade += 0.75

reorder(10,2,1):
[[4 0 1 2 3]
 [9 5 6 7 8]]
reorder(10,2,3):
[[2 3 4 0 1]
 [7 8 9 5 6]]
reorder(10,2,97):
[[3 4 0 1 2]
 [8 9 5 6 7]]


### Problem 8   (2 points) 5-10min.

Write a function taking a list of lists as an argument and returning the number of unique arrays that can be formed by picking exactly one element from each subarray (the first element from the first array the second from the second etc).

**Example**

`solve([[1,2],[4],[5,6]]) = 4`,
because it results in only 4 possiblites, which are `[1,4,5],[1,4,6],[2,4,5],[2,4,6]`.

`solve([[1,2],[4,4],[5,6,6]]) = 4`, 
since the extra outcomes are just duplicates.

You can use NumPy to solve this problem.

In [175]:

def solve1(arrays):
    N = len(arrays)
    compt=0
    for i in range(N):
        combi = []
        for j in range(N):
            if (i >> j) % 2 == 1:
                combi.append(np.unique(arrays[j]))
                compt+=1
        
    return compt
    

In [223]:
#updating version code
def solve(arrays): 
   combi=[]
   combi.append([item[0] for item in arrays])
   combi.append([item[1] for item in arrays])

   print('possible combinations', combi)
   print('number of combinations:')
   return len(combi)

  


In [224]:
print(solve([[1,2],[4,4],[5,6,6]]))
print(solve([[1,2],[4,4],[5,6,7]])) # correct answer is 6
print(solve([[1,2],[4,6]])) # correct answer is 4
#grade += 0

[[1, 4, 5], [2, 4, 6]]
2
[[1, 4, 5], [2, 4, 6]]
2
[[1, 4], [2, 6]]
2


### Problem 9   (2 points) 10min.

Someone has been killed!, and you know every person who those suspects have seen on the day of the murders.

You should:
Write a function taking a dictionary with all the names of the suspects and everyone that they have seen on that day and a list of the names of the dead people and returning the name of the one killer.

**Example**

`suspect_info = {'James': ['Jacob', 'Bill', 'Lucas'],
                 'Johnny': ['David', 'Kyle', 'Lucas'],
                 'Peter': ['Lucy', 'Kyle']}
dead = ['Lucas', 'Bill']
killer(suspect_info, dead) = 'James'`, 
because he is the only person that saw both 'Lucas' and 'Bill'

In [190]:
#updating algorithm version killer program
def killer(suspect_info, dead):
  #person: empty list
  person=[]
  deadpersones=[]
  for i in range(len(dead)):
    deadpersones.append(dead[i])
  print(deadpersones)
  #print(suspect_info)
  #print(dead)
  for suspect, seen in suspect_info.items():
    #If size of dead array is equals to len(value associated by a key) minus 1
    #And if people from array dead are among values for a suspect_info
    if len(dead)<=len(seen) and deadpersones[0] in seen and deadpersones[1] in seen:
      #add the suspect
      person.append(suspect)
      print(seen)
  #return the killer who saw the people in dead
  print('The killer is: ')
  return person

#grade += 0

In [191]:
#test 1
suspect_info = {'James': ['Jacob', 'Bill', 'Lucas'], 'Johnny': ['David', 'Kyle', 'Lucas'], 'Peter': ['Lucy', 'Kyle']}
dead = ['Lucas', 'Bill']
#expected killer:James
killer(suspect_info, dead)

['Lucas', 'Bill']
['Jacob', 'Bill', 'Lucas']
The killer is: 


['James']

In [164]:
#test 2 replacing Bill by Kyle
suspect_info = {'James': ['Jacob', 'Bill', 'Lucas'], 'Johnny': ['David', 'Kyle', 'Lucas'], 'Peter': ['Lucy', 'Kyle']}
dead = ['Lucas','Kyle']
#expected killer: Johnny
killer(suspect_info, dead)

['Lucas', 'Kyle']
['David', 'Kyle', 'Lucas']
The killer is: 


['Johnny']

In [165]:
#test 3 replacing Kyle by Jacob
suspect_info = {'James': ['Jacob', 'Bill', 'Lucas'], 'Johnny': ['David', 'Kyle', 'Lucas'], 'Peter': ['Lucy', 'Kyle']}
dead = ['Lucas','Jacob']
#expected killer:James
killer(suspect_info, dead)

['Lucas', 'Jacob']
['Jacob', 'Bill', 'Lucas']
The killer is: 


['James']

In [119]:
import matplotlib.pyplot as plt

### Problem 10  (6 points) 30min.

You are given a standard dataset iris (do not forget to put csv file in the same directory as this notebook or to change the path to the cav accordingly).

Do the following using pandas library: 

a) Find	the	mean and standard deviation	of the sepal and petal width and length	for	each type of species.

b) Create a new	column called `class` in the iris dataset. The `class` is `short` if `sepal_length` is less	than 5,	and is `long` otherwise.

c) Create a histogram of the `petal_length variable` for each type of species.

d) Do scatter plots of `petal_length` as function of `sepal_length`, same for the width. (Use `plt.scatter`)

e) Using the following formulae write functions to calculate a slope and an intercept of the regression line from the data

Sample regression line:
\begin{equation}
Y_i = \beta_0 + \beta_1 X_i + \epsilon_i,
\end{equation}

Sample slope:
\begin{equation}
\beta_1 = \frac{\sum(X_i – \bar{X}) (Y_i – \bar{Y})} {\sum(X_i – \bar{X})^2},
\end{equation}

Sample intercept:
\begin{equation}
\beta_0 = \bar{Y} – \beta_1 \bar{X},
\end{equation}
where 
\begin{equation}
\bar{y} = \frac{1}{n}\sum_{i=1}^n y_i
\end{equation}

**Example**

    def slope(x, y):
        # your code here
        return beta1
    
    def intercept(x, y):
        # your code here
        return beta0
f) Apply functions from `e)` to calculate linear dependencies for the data from `d)`, put the obtained lines on the same scatter plot (using `plt.plot`).

In [ ]:
import pandas as ps
import matplotlib.pyplot as plt
iris = ps.read_csv('iris.csv')

In [ ]:
iris

In [ ]:

iris[['sepal_length','sepal_width','petal_length','petal_width']].values.mean() 


# second try updating answer question mean by each species
iris.groupby(['Species'])['sepal_length', 'sepal_width', 'petal_length', 'petal_width'].mean()



In [ ]:
#iris std
iris.std()


#second try updating answer question std by each species
iris.groupby(['Species'])['sepal_length', 'sepal_width', 'petal_length', 'petal_width'].std()

In [ ]:
#iris.insert(6,'class', iris['sepal_length']<5'short')

iris['class'] = np.where(iris['sepal_length'] <5, 'short', 'long')



grade += 0.5

In [ ]:
# second try updated version 20/11 iris ['class'] condition  The class is short if sepal_length is less than 5, and is long otherwise.
iris['class'] = ['short' if x <=5  else 'long' for x in iris['sepal_length']] 

In [ ]:
plt.hist(iris['petal_length'])

In [ ]:
# updated version hist version
# subdivise our data into 3 parts corresponding to 3 different types iris-setosa, iris-virginica and iris-versicolor

irissetosa=iris.loc[iris["type"]=="Iris-setosa"]
irisvirginica=iris.loc[iris["type"]=="Iris-virginica"]
irisversicolor=iris.loc[iris["type"]=="Iris-versicolor"]


#1. histogram for iris_setosa
countsiris_setosa,bin_edges=np.histogram(irissetosa["petal_length"],bins=20,density=True)
pdfiris_setosa=counts/(sum(countsiris_setos))
print(pdfiris_setosa)
print(bin_edges)


#cumulative sum
cdpdfiris_setosa=np.cumsum(pdf)
plt.plot(bin_edges[1:],pdfiris_setosa)
plt.plot(bin_edges[1:],cdpdfiris_setosa)
plt.show()


#2.histogram for iris_virginica
countsiris_virginica,bin_edges=np.histogram(irisvirginica["petal_length"],bins=20,density=True)
pdfiris_virginica=counts/(sum(countsiris_virginica))
print(pdfiris_virginica)
print(bin_edges)


#cumulative sum
cdfpdfiris_virginica=np.cumsum(pdfpdfiris_virginica)
plt.plot(bin_edges[1:],pdfiris_virginica)
plt.plot(bin_edges[1:],cdfpdfiris_virginica)
plt.show()


#3.histogram for iris_versicolor
countsiris_versicolor,bin_edges=np.histogram(irisversicolor["petal_length"],bins=10,density=True)
pdfiris_versicolor=counts/(sum(countsiris_versicolor))
print(pdfiris_versicolor)
print(bin_edges)
#cumulative sum
cdiris_versicolorf=np.cumsum(pdfiris_versicolor)
plt.plot(bin_edges[1:],pdfiris_versicolor)
plt.plot(bin_edges[1:],cdfiris_versicolor)
plt.show()

In [ ]:
plt.scatter(iris['sepal_length'],iris['petal_length'])

#add petal_width scatter
plt.scatter(iris['sepal_width'],iris['petal_width'], marker='o')#20/11/2020 adding
grade += 0.5

In [ ]:
#updating code version slope method 
def slope(x, y):
    #numerator of beta1
    betanumerator=0
    #denominator of beta1
    betadenominator=0
    #update betanumerator value with sum symbol 
    for i in range(len(x)):
       #update betanumerator value with sum symbol with axis=1
      betanumerator+=(x[i]-np.mean(x,axis=1))*(y[i]-np.mean(y,axis=1))
    for j in range(len(x)):
      #update betadenominator value with sum symbol with axis=1
      betadenominator+=(x[j]-np.mean(x,axis=1))**2 
    beta1=betanumerator/betadenominator
    return beta1

In [ ]:
#updating code version intercept method
def intercept(x, y):
    #BETA1 value equals to the return value of slope method
    beta1=slope(x,y)
    #apply the function with np.mean(x,axis=1)
    beta0=np.mean(y,axis=1)-beta1*np.mean(x,axis=1)
    return beta0

In [ ]:
grade += 1 # though the code does not work correctly

In [ ]:
result=slope(iris['sepal_length'],iris['petal_length'])

In [ ]:
print('Result: ', result)